### ISSUE TITLE
New meterpreter

### ISSUE THREAD

**Issue by mubix** [kost/nanomet#1]
With the new changes to meterpreter it seems that none of the payloads no longer work at least for me.

REVERSE_HTTPS:

```
Error: HttpSendRequest()
```

REVERSE_TCP:

```
Error: connect()
GetLastError:10061
```

**Comment by mubix** [comment]
Nevermind I was having issues with ports for reverse_tcp, it works now, reverse_https still doesn't

**Comment by mubix** [comment]
Nevermind... borked reverse_https myself too... nothing to see here ;-)

**Comment by kost** [comment]
Glad that things get fixed by themselves ;) hope you're having fun with nanomet ;)
